FROM mcr.microsoft.com/playwright:v1.43.1-noble

WORKDIR /app

COPY package*.json ./
COPY prisma ./prisma/

RUN npm ci

RUN npx prisma generate
RUN npx playwright install chromium

COPY . .

EXPOSE 8080
CMD ["node", "--max-old-space-size=512", "-r", "ts-node/register", "src/server.ts"]